baseurl = "https://chris-prener.github.io/mcat/"
languageCode = "en-us"
title = "MCAT Prep"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Christopher Prener, Ph.D."
	description = "Materials for MCAT Sociology and Psychology Prep Course"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []

	# Ignore files
	ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**MCAT** </br> slides from chris's sociology </br>and psychology prep course"
		# The icons will be shown if you enter your username
		twitter = "chrisprener"
		github = "chris-prener"
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""
		# homepage url
		home="https://chris-prener.github.io/"
		
		copyright = [
			"&copy; 2018 [CC-BY-SA 4.0](/mcat/license)",
			"Design: [HTML5 UP](//html5up.net)",
			"Cover Image: [M. Alizade](https://unsplash.com/@mohamadaz?utm_medium=referral)"
		]

  [params.avatar]
    hide = true

	[params.about]
		hide  = false
		title = "Reviewing the Psychosocial Approach to Health"
		content = "This site provides access to slides from my MCAT preparation course, which covers content from the [Psychological, Social, and Biological Foundations of Behavior Section](https://students-residents.aamc.org/applying-medical-school/article/mcat-2015-psbb-overview/) of the MCAT. The course is sponsored by [Saint Louis University's](http://www.slu.edu) [Alpha Epsilon Delta chapter](https://groups.sluconnection.com/organization/AED)."


	[params.portfolio]
		hide  = true
		title = "Recent Work"

	[params.recentposts]
		hide  = true
		title = "recent articles"

	[params.contact]
		hide  = true
		email = "chris.prener@slu.edu"

# Menu links that appear on the left sidebar
[[menu.main]]
	name = "home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "lecture 01"
	url  = "/lecture01"
	weight = 20

[[menu.main]]
	name = "lecture 02"
	url  = "/lecture02"
	weight = 21
	
[[menu.main]]
	name = "lecture 03"
	url  = "/lecture03"
	weight = 22
	
[[menu.main]]
	name = "lecture 04"
	url  = "/lecture04"
	weight = 23
	
[[menu.main]]
	name = "lecture 05"
	url  = "/lecture05"
	weight = 24

[[menu.main]]
	name = "credits"
	url  = "/credits"
	weight = 44
	
[[menu.main]]
	name = "license"
	url  = "/license"
	weight = 45